/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresIndexRouteImport } from './routes/stores.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as STenantRouteImport } from './routes/s.$tenant'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as STenantIndexRouteImport } from './routes/s.$tenant.index'
import { Route as STenantWishlistRouteImport } from './routes/s.$tenant.wishlist'
import { Route as STenantSearchRouteImport } from './routes/s.$tenant.search'
import { Route as STenantCheckoutRouteImport } from './routes/s.$tenant.checkout'
import { Route as STenantCartRouteImport } from './routes/s.$tenant.cart'
import { Route as STenantAdminRouteImport } from './routes/s.$tenant.admin'
import { Route as STenantAccountRouteImport } from './routes/s.$tenant.account'
import { Route as STenantOrdersIndexRouteImport } from './routes/s.$tenant.orders.index'
import { Route as STenantAdminIndexRouteImport } from './routes/s.$tenant.admin.index'
import { Route as STenantPProductIdRouteImport } from './routes/s.$tenant.p.$productId'
import { Route as STenantOrdersIdRouteImport } from './routes/s.$tenant.orders.$id'
import { Route as STenantCCategoryRouteImport } from './routes/s.$tenant.c.$category'
import { Route as STenantAdminSettingsRouteImport } from './routes/s.$tenant.admin.settings'
import { Route as STenantAdminReportsRouteImport } from './routes/s.$tenant.admin.reports'
import { Route as STenantAdminNotificationsRouteImport } from './routes/s.$tenant.admin.notifications'
import { Route as STenantAdminCustomersRouteImport } from './routes/s.$tenant.admin.customers'
import { Route as STenantAdminCouponsRouteImport } from './routes/s.$tenant.admin.coupons'
import { Route as STenantAdminCategoriesRouteImport } from './routes/s.$tenant.admin.categories'
import { Route as STenantAdminProductsIndexRouteImport } from './routes/s.$tenant.admin.products.index'
import { Route as STenantAdminOrdersIndexRouteImport } from './routes/s.$tenant.admin.orders.index'
import { Route as STenantAdminProductsNewRouteImport } from './routes/s.$tenant.admin.products.new'
import { Route as STenantAdminProductsIdRouteImport } from './routes/s.$tenant.admin.products.$id'
import { Route as STenantAdminOrdersIdRouteImport } from './routes/s.$tenant.admin.orders.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const STenantRoute = STenantRouteImport.update({
  id: '/s/$tenant',
  path: '/s/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const STenantIndexRoute = STenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => STenantRoute,
} as any)
const STenantWishlistRoute = STenantWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => STenantRoute,
} as any)
const STenantSearchRoute = STenantSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => STenantRoute,
} as any)
const STenantCheckoutRoute = STenantCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => STenantRoute,
} as any)
const STenantCartRoute = STenantCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => STenantRoute,
} as any)
const STenantAdminRoute = STenantAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => STenantRoute,
} as any)
const STenantAccountRoute = STenantAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => STenantRoute,
} as any)
const STenantOrdersIndexRoute = STenantOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => STenantRoute,
} as any)
const STenantAdminIndexRoute = STenantAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => STenantAdminRoute,
} as any)
const STenantPProductIdRoute = STenantPProductIdRouteImport.update({
  id: '/p/$productId',
  path: '/p/$productId',
  getParentRoute: () => STenantRoute,
} as any)
const STenantOrdersIdRoute = STenantOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => STenantRoute,
} as any)
const STenantCCategoryRoute = STenantCCategoryRouteImport.update({
  id: '/c/$category',
  path: '/c/$category',
  getParentRoute: () => STenantRoute,
} as any)
const STenantAdminSettingsRoute = STenantAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => STenantAdminRoute,
} as any)
const STenantAdminReportsRoute = STenantAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => STenantAdminRoute,
} as any)
const STenantAdminNotificationsRoute =
  STenantAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => STenantAdminRoute,
  } as any)
const STenantAdminCustomersRoute = STenantAdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => STenantAdminRoute,
} as any)
const STenantAdminCouponsRoute = STenantAdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => STenantAdminRoute,
} as any)
const STenantAdminCategoriesRoute = STenantAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => STenantAdminRoute,
} as any)
const STenantAdminProductsIndexRoute =
  STenantAdminProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => STenantAdminRoute,
  } as any)
const STenantAdminOrdersIndexRoute = STenantAdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => STenantAdminRoute,
} as any)
const STenantAdminProductsNewRoute = STenantAdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => STenantAdminRoute,
} as any)
const STenantAdminProductsIdRoute = STenantAdminProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => STenantAdminRoute,
} as any)
const STenantAdminOrdersIdRoute = STenantAdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => STenantAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/s/$tenant': typeof STenantRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/s/$tenant/account': typeof STenantAccountRoute
  '/s/$tenant/admin': typeof STenantAdminRouteWithChildren
  '/s/$tenant/cart': typeof STenantCartRoute
  '/s/$tenant/checkout': typeof STenantCheckoutRoute
  '/s/$tenant/search': typeof STenantSearchRoute
  '/s/$tenant/wishlist': typeof STenantWishlistRoute
  '/s/$tenant/': typeof STenantIndexRoute
  '/s/$tenant/admin/categories': typeof STenantAdminCategoriesRoute
  '/s/$tenant/admin/coupons': typeof STenantAdminCouponsRoute
  '/s/$tenant/admin/customers': typeof STenantAdminCustomersRoute
  '/s/$tenant/admin/notifications': typeof STenantAdminNotificationsRoute
  '/s/$tenant/admin/reports': typeof STenantAdminReportsRoute
  '/s/$tenant/admin/settings': typeof STenantAdminSettingsRoute
  '/s/$tenant/c/$category': typeof STenantCCategoryRoute
  '/s/$tenant/orders/$id': typeof STenantOrdersIdRoute
  '/s/$tenant/p/$productId': typeof STenantPProductIdRoute
  '/s/$tenant/admin/': typeof STenantAdminIndexRoute
  '/s/$tenant/orders/': typeof STenantOrdersIndexRoute
  '/s/$tenant/admin/orders/$id': typeof STenantAdminOrdersIdRoute
  '/s/$tenant/admin/products/$id': typeof STenantAdminProductsIdRoute
  '/s/$tenant/admin/products/new': typeof STenantAdminProductsNewRoute
  '/s/$tenant/admin/orders/': typeof STenantAdminOrdersIndexRoute
  '/s/$tenant/admin/products/': typeof STenantAdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin': typeof AdminIndexRoute
  '/stores': typeof StoresIndexRoute
  '/s/$tenant/account': typeof STenantAccountRoute
  '/s/$tenant/cart': typeof STenantCartRoute
  '/s/$tenant/checkout': typeof STenantCheckoutRoute
  '/s/$tenant/search': typeof STenantSearchRoute
  '/s/$tenant/wishlist': typeof STenantWishlistRoute
  '/s/$tenant': typeof STenantIndexRoute
  '/s/$tenant/admin/categories': typeof STenantAdminCategoriesRoute
  '/s/$tenant/admin/coupons': typeof STenantAdminCouponsRoute
  '/s/$tenant/admin/customers': typeof STenantAdminCustomersRoute
  '/s/$tenant/admin/notifications': typeof STenantAdminNotificationsRoute
  '/s/$tenant/admin/reports': typeof STenantAdminReportsRoute
  '/s/$tenant/admin/settings': typeof STenantAdminSettingsRoute
  '/s/$tenant/c/$category': typeof STenantCCategoryRoute
  '/s/$tenant/orders/$id': typeof STenantOrdersIdRoute
  '/s/$tenant/p/$productId': typeof STenantPProductIdRoute
  '/s/$tenant/admin': typeof STenantAdminIndexRoute
  '/s/$tenant/orders': typeof STenantOrdersIndexRoute
  '/s/$tenant/admin/orders/$id': typeof STenantAdminOrdersIdRoute
  '/s/$tenant/admin/products/$id': typeof STenantAdminProductsIdRoute
  '/s/$tenant/admin/products/new': typeof STenantAdminProductsNewRoute
  '/s/$tenant/admin/orders': typeof STenantAdminOrdersIndexRoute
  '/s/$tenant/admin/products': typeof STenantAdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/s/$tenant': typeof STenantRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/s/$tenant/account': typeof STenantAccountRoute
  '/s/$tenant/admin': typeof STenantAdminRouteWithChildren
  '/s/$tenant/cart': typeof STenantCartRoute
  '/s/$tenant/checkout': typeof STenantCheckoutRoute
  '/s/$tenant/search': typeof STenantSearchRoute
  '/s/$tenant/wishlist': typeof STenantWishlistRoute
  '/s/$tenant/': typeof STenantIndexRoute
  '/s/$tenant/admin/categories': typeof STenantAdminCategoriesRoute
  '/s/$tenant/admin/coupons': typeof STenantAdminCouponsRoute
  '/s/$tenant/admin/customers': typeof STenantAdminCustomersRoute
  '/s/$tenant/admin/notifications': typeof STenantAdminNotificationsRoute
  '/s/$tenant/admin/reports': typeof STenantAdminReportsRoute
  '/s/$tenant/admin/settings': typeof STenantAdminSettingsRoute
  '/s/$tenant/c/$category': typeof STenantCCategoryRoute
  '/s/$tenant/orders/$id': typeof STenantOrdersIdRoute
  '/s/$tenant/p/$productId': typeof STenantPProductIdRoute
  '/s/$tenant/admin/': typeof STenantAdminIndexRoute
  '/s/$tenant/orders/': typeof STenantOrdersIndexRoute
  '/s/$tenant/admin/orders/$id': typeof STenantAdminOrdersIdRoute
  '/s/$tenant/admin/products/$id': typeof STenantAdminProductsIdRoute
  '/s/$tenant/admin/products/new': typeof STenantAdminProductsNewRoute
  '/s/$tenant/admin/orders/': typeof STenantAdminOrdersIndexRoute
  '/s/$tenant/admin/products/': typeof STenantAdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/tenants'
    | '/auth/login'
    | '/auth/signup'
    | '/s/$tenant'
    | '/admin/'
    | '/stores/'
    | '/s/$tenant/account'
    | '/s/$tenant/admin'
    | '/s/$tenant/cart'
    | '/s/$tenant/checkout'
    | '/s/$tenant/search'
    | '/s/$tenant/wishlist'
    | '/s/$tenant/'
    | '/s/$tenant/admin/categories'
    | '/s/$tenant/admin/coupons'
    | '/s/$tenant/admin/customers'
    | '/s/$tenant/admin/notifications'
    | '/s/$tenant/admin/reports'
    | '/s/$tenant/admin/settings'
    | '/s/$tenant/c/$category'
    | '/s/$tenant/orders/$id'
    | '/s/$tenant/p/$productId'
    | '/s/$tenant/admin/'
    | '/s/$tenant/orders/'
    | '/s/$tenant/admin/orders/$id'
    | '/s/$tenant/admin/products/$id'
    | '/s/$tenant/admin/products/new'
    | '/s/$tenant/admin/orders/'
    | '/s/$tenant/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/analytics'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/tenants'
    | '/auth/login'
    | '/auth/signup'
    | '/admin'
    | '/stores'
    | '/s/$tenant/account'
    | '/s/$tenant/cart'
    | '/s/$tenant/checkout'
    | '/s/$tenant/search'
    | '/s/$tenant/wishlist'
    | '/s/$tenant'
    | '/s/$tenant/admin/categories'
    | '/s/$tenant/admin/coupons'
    | '/s/$tenant/admin/customers'
    | '/s/$tenant/admin/notifications'
    | '/s/$tenant/admin/reports'
    | '/s/$tenant/admin/settings'
    | '/s/$tenant/c/$category'
    | '/s/$tenant/orders/$id'
    | '/s/$tenant/p/$productId'
    | '/s/$tenant/admin'
    | '/s/$tenant/orders'
    | '/s/$tenant/admin/orders/$id'
    | '/s/$tenant/admin/products/$id'
    | '/s/$tenant/admin/products/new'
    | '/s/$tenant/admin/orders'
    | '/s/$tenant/admin/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/tenants'
    | '/auth/login'
    | '/auth/signup'
    | '/s/$tenant'
    | '/admin/'
    | '/stores/'
    | '/s/$tenant/account'
    | '/s/$tenant/admin'
    | '/s/$tenant/cart'
    | '/s/$tenant/checkout'
    | '/s/$tenant/search'
    | '/s/$tenant/wishlist'
    | '/s/$tenant/'
    | '/s/$tenant/admin/categories'
    | '/s/$tenant/admin/coupons'
    | '/s/$tenant/admin/customers'
    | '/s/$tenant/admin/notifications'
    | '/s/$tenant/admin/reports'
    | '/s/$tenant/admin/settings'
    | '/s/$tenant/c/$category'
    | '/s/$tenant/orders/$id'
    | '/s/$tenant/p/$productId'
    | '/s/$tenant/admin/'
    | '/s/$tenant/orders/'
    | '/s/$tenant/admin/orders/$id'
    | '/s/$tenant/admin/products/$id'
    | '/s/$tenant/admin/products/new'
    | '/s/$tenant/admin/orders/'
    | '/s/$tenant/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  STenantRoute: typeof STenantRouteWithChildren
  StoresIndexRoute: typeof StoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$tenant': {
      id: '/s/$tenant'
      path: '/s/$tenant'
      fullPath: '/s/$tenant'
      preLoaderRoute: typeof STenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$tenant/': {
      id: '/s/$tenant/'
      path: '/'
      fullPath: '/s/$tenant/'
      preLoaderRoute: typeof STenantIndexRouteImport
      parentRoute: typeof STenantRoute
    }
    '/s/$tenant/wishlist': {
      id: '/s/$tenant/wishlist'
      path: '/wishlist'
      fullPath: '/s/$tenant/wishlist'
      preLoaderRoute: typeof STenantWishlistRouteImport
      parentRoute: typeof STenantRoute
    }
    '/s/$tenant/search': {
      id: '/s/$tenant/search'
      path: '/search'
      fullPath: '/s/$tenant/search'
      preLoaderRoute: typeof STenantSearchRouteImport
      parentRoute: typeof STenantRoute
    }
    '/s/$tenant/checkout': {
      id: '/s/$tenant/checkout'
      path: '/checkout'
      fullPath: '/s/$tenant/checkout'
      preLoaderRoute: typeof STenantCheckoutRouteImport
      parentRoute: typeof STenantRoute
    }
    '/s/$tenant/cart': {
      id: '/s/$tenant/cart'
      path: '/cart'
      fullPath: '/s/$tenant/cart'
      preLoaderRoute: typeof STenantCartRouteImport
      parentRoute: typeof STenantRoute
    }
    '/s/$tenant/admin': {
      id: '/s/$tenant/admin'
      path: '/admin'
      fullPath: '/s/$tenant/admin'
      preLoaderRoute: typeof STenantAdminRouteImport
      parentRoute: typeof STenantRoute
    }
    '/s/$tenant/account': {
      id: '/s/$tenant/account'
      path: '/account'
      fullPath: '/s/$tenant/account'
      preLoaderRoute: typeof STenantAccountRouteImport
      parentRoute: typeof STenantRoute
    }
    '/s/$tenant/orders/': {
      id: '/s/$tenant/orders/'
      path: '/orders'
      fullPath: '/s/$tenant/orders/'
      preLoaderRoute: typeof STenantOrdersIndexRouteImport
      parentRoute: typeof STenantRoute
    }
    '/s/$tenant/admin/': {
      id: '/s/$tenant/admin/'
      path: '/'
      fullPath: '/s/$tenant/admin/'
      preLoaderRoute: typeof STenantAdminIndexRouteImport
      parentRoute: typeof STenantAdminRoute
    }
    '/s/$tenant/p/$productId': {
      id: '/s/$tenant/p/$productId'
      path: '/p/$productId'
      fullPath: '/s/$tenant/p/$productId'
      preLoaderRoute: typeof STenantPProductIdRouteImport
      parentRoute: typeof STenantRoute
    }
    '/s/$tenant/orders/$id': {
      id: '/s/$tenant/orders/$id'
      path: '/orders/$id'
      fullPath: '/s/$tenant/orders/$id'
      preLoaderRoute: typeof STenantOrdersIdRouteImport
      parentRoute: typeof STenantRoute
    }
    '/s/$tenant/c/$category': {
      id: '/s/$tenant/c/$category'
      path: '/c/$category'
      fullPath: '/s/$tenant/c/$category'
      preLoaderRoute: typeof STenantCCategoryRouteImport
      parentRoute: typeof STenantRoute
    }
    '/s/$tenant/admin/settings': {
      id: '/s/$tenant/admin/settings'
      path: '/settings'
      fullPath: '/s/$tenant/admin/settings'
      preLoaderRoute: typeof STenantAdminSettingsRouteImport
      parentRoute: typeof STenantAdminRoute
    }
    '/s/$tenant/admin/reports': {
      id: '/s/$tenant/admin/reports'
      path: '/reports'
      fullPath: '/s/$tenant/admin/reports'
      preLoaderRoute: typeof STenantAdminReportsRouteImport
      parentRoute: typeof STenantAdminRoute
    }
    '/s/$tenant/admin/notifications': {
      id: '/s/$tenant/admin/notifications'
      path: '/notifications'
      fullPath: '/s/$tenant/admin/notifications'
      preLoaderRoute: typeof STenantAdminNotificationsRouteImport
      parentRoute: typeof STenantAdminRoute
    }
    '/s/$tenant/admin/customers': {
      id: '/s/$tenant/admin/customers'
      path: '/customers'
      fullPath: '/s/$tenant/admin/customers'
      preLoaderRoute: typeof STenantAdminCustomersRouteImport
      parentRoute: typeof STenantAdminRoute
    }
    '/s/$tenant/admin/coupons': {
      id: '/s/$tenant/admin/coupons'
      path: '/coupons'
      fullPath: '/s/$tenant/admin/coupons'
      preLoaderRoute: typeof STenantAdminCouponsRouteImport
      parentRoute: typeof STenantAdminRoute
    }
    '/s/$tenant/admin/categories': {
      id: '/s/$tenant/admin/categories'
      path: '/categories'
      fullPath: '/s/$tenant/admin/categories'
      preLoaderRoute: typeof STenantAdminCategoriesRouteImport
      parentRoute: typeof STenantAdminRoute
    }
    '/s/$tenant/admin/products/': {
      id: '/s/$tenant/admin/products/'
      path: '/products'
      fullPath: '/s/$tenant/admin/products/'
      preLoaderRoute: typeof STenantAdminProductsIndexRouteImport
      parentRoute: typeof STenantAdminRoute
    }
    '/s/$tenant/admin/orders/': {
      id: '/s/$tenant/admin/orders/'
      path: '/orders'
      fullPath: '/s/$tenant/admin/orders/'
      preLoaderRoute: typeof STenantAdminOrdersIndexRouteImport
      parentRoute: typeof STenantAdminRoute
    }
    '/s/$tenant/admin/products/new': {
      id: '/s/$tenant/admin/products/new'
      path: '/products/new'
      fullPath: '/s/$tenant/admin/products/new'
      preLoaderRoute: typeof STenantAdminProductsNewRouteImport
      parentRoute: typeof STenantAdminRoute
    }
    '/s/$tenant/admin/products/$id': {
      id: '/s/$tenant/admin/products/$id'
      path: '/products/$id'
      fullPath: '/s/$tenant/admin/products/$id'
      preLoaderRoute: typeof STenantAdminProductsIdRouteImport
      parentRoute: typeof STenantAdminRoute
    }
    '/s/$tenant/admin/orders/$id': {
      id: '/s/$tenant/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/s/$tenant/admin/orders/$id'
      preLoaderRoute: typeof STenantAdminOrdersIdRouteImport
      parentRoute: typeof STenantAdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface STenantAdminRouteChildren {
  STenantAdminCategoriesRoute: typeof STenantAdminCategoriesRoute
  STenantAdminCouponsRoute: typeof STenantAdminCouponsRoute
  STenantAdminCustomersRoute: typeof STenantAdminCustomersRoute
  STenantAdminNotificationsRoute: typeof STenantAdminNotificationsRoute
  STenantAdminReportsRoute: typeof STenantAdminReportsRoute
  STenantAdminSettingsRoute: typeof STenantAdminSettingsRoute
  STenantAdminIndexRoute: typeof STenantAdminIndexRoute
  STenantAdminOrdersIdRoute: typeof STenantAdminOrdersIdRoute
  STenantAdminProductsIdRoute: typeof STenantAdminProductsIdRoute
  STenantAdminProductsNewRoute: typeof STenantAdminProductsNewRoute
  STenantAdminOrdersIndexRoute: typeof STenantAdminOrdersIndexRoute
  STenantAdminProductsIndexRoute: typeof STenantAdminProductsIndexRoute
}

const STenantAdminRouteChildren: STenantAdminRouteChildren = {
  STenantAdminCategoriesRoute: STenantAdminCategoriesRoute,
  STenantAdminCouponsRoute: STenantAdminCouponsRoute,
  STenantAdminCustomersRoute: STenantAdminCustomersRoute,
  STenantAdminNotificationsRoute: STenantAdminNotificationsRoute,
  STenantAdminReportsRoute: STenantAdminReportsRoute,
  STenantAdminSettingsRoute: STenantAdminSettingsRoute,
  STenantAdminIndexRoute: STenantAdminIndexRoute,
  STenantAdminOrdersIdRoute: STenantAdminOrdersIdRoute,
  STenantAdminProductsIdRoute: STenantAdminProductsIdRoute,
  STenantAdminProductsNewRoute: STenantAdminProductsNewRoute,
  STenantAdminOrdersIndexRoute: STenantAdminOrdersIndexRoute,
  STenantAdminProductsIndexRoute: STenantAdminProductsIndexRoute,
}

const STenantAdminRouteWithChildren = STenantAdminRoute._addFileChildren(
  STenantAdminRouteChildren,
)

interface STenantRouteChildren {
  STenantAccountRoute: typeof STenantAccountRoute
  STenantAdminRoute: typeof STenantAdminRouteWithChildren
  STenantCartRoute: typeof STenantCartRoute
  STenantCheckoutRoute: typeof STenantCheckoutRoute
  STenantSearchRoute: typeof STenantSearchRoute
  STenantWishlistRoute: typeof STenantWishlistRoute
  STenantIndexRoute: typeof STenantIndexRoute
  STenantCCategoryRoute: typeof STenantCCategoryRoute
  STenantOrdersIdRoute: typeof STenantOrdersIdRoute
  STenantPProductIdRoute: typeof STenantPProductIdRoute
  STenantOrdersIndexRoute: typeof STenantOrdersIndexRoute
}

const STenantRouteChildren: STenantRouteChildren = {
  STenantAccountRoute: STenantAccountRoute,
  STenantAdminRoute: STenantAdminRouteWithChildren,
  STenantCartRoute: STenantCartRoute,
  STenantCheckoutRoute: STenantCheckoutRoute,
  STenantSearchRoute: STenantSearchRoute,
  STenantWishlistRoute: STenantWishlistRoute,
  STenantIndexRoute: STenantIndexRoute,
  STenantCCategoryRoute: STenantCCategoryRoute,
  STenantOrdersIdRoute: STenantOrdersIdRoute,
  STenantPProductIdRoute: STenantPProductIdRoute,
  STenantOrdersIndexRoute: STenantOrdersIndexRoute,
}

const STenantRouteWithChildren =
  STenantRoute._addFileChildren(STenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  STenantRoute: STenantRouteWithChildren,
  StoresIndexRoute: StoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
